version: "3.3"
services:

  redis:
    image: redis:4.0.9-alpine
    command: redis-server --requirepass 'pass'
    ports:
      - "6379:6379"

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - postgres
      - mongo
    environment:
      - DOCKER=True
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=$PYTHONPATH:/code
      - POETRY_VIRTUALENVS_IN_PROJECT=true
      - SHELL=/bin/bash
    ports:
      - "8888:8888"  # for jupyter notebooks
    volumes:
      - ./:/code
